---
- hosts: all
  tasks: []
  vars:
    webrtc_build_src: ../
    webrtc_dev_gclient:
      url: "https://chromium.googlesource.com/external/webrtc.git@b024da31225ef47470f09798dd745ab99840bb95"
      custom_deps: {}
  roles:
  - common
  - chromium_dev
  - webrtc_dev
  - webrtc_build
