---

- name: install build dependencies
  apt: name={{ item }} state=present
  with_items:
  - g++-4.8-multilib-arm-linux-gnueabihf
  - expect
  when: "{{ ansible_distribution_version | version_compare('13.0', '>=') }}"

- name: add ubuntu toolchain ppa
  apt_repository: repo="ppa:ubuntu-toolchain-r/test"
  when: "{{ ansible_distribution_version | version_compare('13.0', '<') }}"
  register: ubuntu_toolchain_ppa

- name: update apt cache
  apt: update_cache=yes
  tags: [apt]
  when: ubuntu_toolchain_ppa|changed

- name: add linaro toolchain ppa
  apt_repository: repo="ppa:linaro-maintainers/toolchain"
  when: "{{ ansible_distribution_version | version_compare('13.0', '<') }}"
  register: linaro_toolchain_ppa
  tags: [apt]

- name: update apt cache
  apt: update_cache=yes
  tags: [apt]
  when: linaro_toolchain_ppa|changed

- name: install build dependencies
  apt: name={{ item }} state=present
  with_items:
  - g++-4.8-multilib
  - g++-arm-linux-gnueabi
  when: "{{ ansible_distribution_version | version_compare('13.0', '<') }}"

- name: download chromium install build deps script
  get_url: >
    url=https://src.chromium.org/svn/trunk/src/build/install-build-deps.sh
    dest="/tmp/chromium-install-build-deps.sh"
    mode=0755

- name: accept ttf-mscorefonts-installer eula
  debconf:
    name: ttf-mscorefonts-installer
    question: msttcorefonts/accepted-mscorefonts-eula
    value: "true"
    vtype: select

- name: copy expect for chromium install build deps script
  template: >
    src=chromium-install-build-deps.expect.j2
    dest=/tmp/chromium-install-build-deps.expect
    mode=0755

- name: install chromium build deps
  command: /tmp/chromium-install-build-deps.expect
