---
- name: clone depot_tools
  git:
    repo: https://chromium.googlesource.com/chromium/tools/depot_tools.git
    dest: /opt/depot_tools
  sudo: yes

- name: set depot_tools profile
  copy:
    src: etc/profile.d/depot-tools.sh
    dest: /etc/profile.d/depot-tools.sh
    owner: root
    group: root
    mode: 0755
  sudo: yes
