---

- name: create group
  group: name={{ chromium_dev_group }} state=present

- name: create depot_tools dir
  file:
    path: "{{ chromium_dev_root }}/depot_tools"
    state: directory
    group: "{{ chromium_dev_group }}"
    mode: 0775

- name: clone depot_tools
  git:
    repo: https://chromium.googlesource.com/chromium/tools/depot_tools.git
    dest: "{{ chromium_dev_root }}/depot_tools"

- name: copy depot_tools profile
  template:
    src: depot-tools.sh.j2
    dest: "/etc/profile.d/depot-tools.sh"
    mode: 0755
