---
- name: create depot_tools dir
  file: path="{{ chromium_dev_root }}/depot_tools" state=directory mode=0775

- name: clone depot_tools
  git:
    repo: https://chromium.googlesource.com/chromium/tools/depot_tools.git
    dest: "{{ chromium_dev_root }}/depot_tools"

- name: copy depot_tools profile
  template:
    src: depot-tools.sh.j2
    dest: "{{ chromium_dev_root }}/depot-tools.sh"
    mode: 0755

- name: source depot_tools
  lineinfile: >
    dest="~/.bashrc"
    regexp="source .*/depot-tools\.sh"
    line="source {{ chromium_dev_root }}/depot-tools.sh"
    state=present
