---

webrtc_dev_group: build
webrtc_dev_root: /opt
webrtc_dev_gclient:
  url: https://chromium.googlesource.com/external/webrtc.git
  custom_deps: {}
webrtc_dev_rev: 555cfe9e6e093b01142512de09c8f656308cd043
webrtc_dev_ver: "1{{ webrtc_dev_rev[:7] }}"
webrtc_dev_src: "/usr/src/libjingle{{ webrtc_dev_ver }}"
webrtc_dev_skip_checkout: no
webrtc_dev_sysroot: sysroot-creator-wheezy.sh
