---

language: python

python:
- "2.7"

sudo: required

dist: trusty

env:
  global:
  #- AWS_ACCESS_KEY_ID=xxx
  #- AWS_SECRET_ACCESS_KEY=xxx
  #- AWS_INSTANCE_PROFILE=xxx
  #- SECRETS_S3_BUCKET=xxx
  - AWS_IMAGE_ID=ami-d14d08b1
  - AWS_SUBNET_ID=subnet-5ac2623f
  - AWS_SEC_GROUP_ID=sg-52209a36
  - AWS_INSTANCE_TYPE=c4.xlarge
  - APT_S3_BUCKET=apt-tm8ji0.c2x.io
  - AWS_REGION=us-west-1
  - APT_S3_ENDPOINT=s3-us-west-2.amazonaws.com

before_install:
# https://github.com/travis-ci/travis-ci/issues/5326
- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

install:
- sudo pip install "ansible >=2,<3"
- sudo pip install "awscli >=1,<2"
- sudo apt-get update -qq
- sudo apt-get install -y jq gnupg ruby1.9.1 ruby1.9.1-dev
- gem install deb-s3

before_script:
- export TRAVIS_CI_PATH=$(pwd)
- export SCRIPTS_DIR="${TRAVIS_CI_PATH}/scripts"
- export PROVISION_DIR="${TRAVIS_CI_PATH}/provision"
- export TEST_DIR="${TRAVIS_CI_PATH}/test"
- |
  export LIBJINGLE_VER=$(grep -oP 'webrtc_dev_rev: \K\w+' ${PROVISION_DIR}/roles/webrtc_dev/defaults/main.yml | cut -c1-7)
- aws configure set region ${AWS_REGION}
- aws s3 cp s3://${SECRETS_S3_BUCKET}/travis-webrtc-build/id_rsa.pub ~/.ssh/id_rsa.pub
- aws s3 cp s3://${SECRETS_S3_BUCKET}/travis-webrtc-build/id_rsa ~/.ssh/id_rsa
- chmod 0600 ~/.ssh/id_rsa

script:
- ${SCRIPTS_DIR}/travis.d/script

after_success:
- ${SCRIPTS_DIR}/travis.d/after-success

notifications:
  email:
    on_success: change
    on_failure: change
