---

- name: install fpm
  gem: name=fpm state=latest user_install=no
  become: yes
  tags: [webrtc-build]

- name: install python dependencies
  pip: name={{ item }}
  with_items:
  - mako
  become: yes
  tags: [webrtc-build]

- name: sync scripts to webrtc workspace
  synchronize: >
    src={{ role_path }}/../../../scripts
    dest={{ webrtc_dev_root }}/webrtc/
  tags: [webrtc-build]

- name: set scripts owner
  file: >
    path={{ webrtc_dev_root }}/webrtc/scripts/
    group={{ webrtc_dev_group }}
    recurse=yes
  become: yes
  tags: [webrtc-build]
