---
- name: add debian i386 architecture
  command: dpkg --add-architecture i386
  tags: [deb]
  sudo: yes
  when: ansible_os_family == "Debian" and ansible_architecture == "x86_64"

- name: enable apt multiverse
  command: apt-add-repository multiverse
  tags: [apt]
  sudo: yes
  when: ansible_architecture == "x86_64"

- name: update apt cache 
  apt: update_cache=yes cache_valid_time=3600
  tags: [apt]
  sudo: yes

- name: install tools
  apt: name={{ item }} state=present
  with_items:
  - vim
  - htop
  - tmux
  - build-essential
  - git
  - expect
  - openjdk-7-jdk
  - wget
  - gnupg
  - flex
  - bison
  - gperf
  - zip
  - curl
  - subversion
  - pkg-config
  - nethogs
  - python-pip
  - rubygems1.9.1
  - ruby1.9.1-dev
  - python2.7-dev
  tags: [tools]
  sudo: yes

- name: use vim as editor
  alternatives: name=editor path=/usr/bin/vim
  tags: [tools]
  sudo: yes

- name: use openjdk-7 as java
  alternatives: name=java path=/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
  tags: [tools]
  sudo: yes

- name: set java profile
  copy:
    src: etc/profile.d/java.sh
    dest: /etc/profile.d/java.sh
    owner: root
    group: root
    mode: 0755
  tags: [tools]
  sudo: yes
