---
- name: add debian i386 architecture
  command: dpkg --add-architecture i386
  tags: [deb]
  become: yes
  when: ansible_os_family == "Debian" and ansible_architecture == "x86_64" and {{ ansible_distribution_version | version_compare('13.0', '>=') }}

- name: add debian i386 architecture
  lineinfile: dest=/etc/dpkg/dpkg.cfg.d/multiarch line="foreign-architecture i386"
  tags: [deb]
  become: yes
  when: ansible_os_family == "Debian" and ansible_architecture == "x86_64" and {{ ansible_distribution_version | version_compare('13.0', '<') }}

- name: enable apt multiverse
  command: apt-add-repository multiverse
  tags: [apt]
  become: yes
  when: ansible_os_family == "Debian" and {{ ansible_distribution_version | version_compare('13.0', '>=') }}

- name: enable apt multiverse
  template:
    src: etc/apt/sources.list.d/multiverse.list.j2
    dest: /etc/apt/sources.list.d/multiverse.list
    mode: 0755
  tags: [apt]
  become: yes
  when: ansible_os_family == "Debian" and {{ ansible_distribution_version | version_compare('13.0', '<') }}

- name: update apt cache 
  apt: update_cache=yes cache_valid_time=3600
  tags: [apt]
  become: yes

- name: install tools
  apt: name={{ item }} state=present
  with_items:
  - vim
  - htop
  - tmux
  - build-essential
  - git
  - expect
  - openjdk-7-jdk
  - wget
  - gnupg
  - flex
  - bison
  - gperf
  - zip
  - curl
  - subversion
  - pkg-config
  - nethogs
  - python-pip
  - ruby-dev
  - python2.7-dev
  - tree
  - at
  tags: [tools]
  become: yes

- name: use vim as editor
  alternatives: name=editor path=/usr/bin/vim.basic
  tags: [tools]
  become: yes

- name: use openjdk-7 as java
  alternatives: name=java path=/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
  tags: [tools]
  become: yes

- name: set java profile
  copy:
    src: etc/profile.d/java.sh
    dest: /etc/profile.d/java.sh
    owner: root
    group: root
    mode: 0755
  tags: [tools]
  become: yes
