---
- include: network.yml
  tags: [common, network]

- include: swap.yml
  when: ansible_memtotal_mb < 2048
  tags: [common, swap]

- include: dependencies.yml
  tags: [common, deps]
  
- include: users.yml
  tags: [common, users]
  
- include: git.yml
  tags: [common, git]
