---
- name: copy resolvconf
  copy:
    src: etc/resolvconf/resolv.conf.d/base
    dest: /etc/resolvconf/resolv.conf.d/base
    owner: root
    group: root
    mode: 0644
  tags: [dns]
  register: resolvconf
  sudo: yes

- name: update resolvconf
  command: /sbin/resolvconf -u
  sudo: yes
  when: resolvconf|changed
