---

- name: bashrc
  copy:
    src: etc/profile.d/bashrc.sh
    dest: /etc/profile.d/bashrc.sh
    owner: root
    group: root
    mode: 0755
  become: yes

- name: bash aliases
  copy:
    src: etc/profile.d/bash_aliases.sh
    dest: /etc/profile.d/bash_aliases.sh
    owner: root
    group: root
    mode: 0755
  become: yes

- name: create dev group
  group: name={{ common_dev_group }} state=present
  become: yes

- name: add users to dev group
  user: name={{ item }} groups={{ common_dev_group }} append=yes
  with_items: "{{ common_dev_users }}"
  become: yes
