---
- name: bashrc
  copy:
    src: etc/profile.d/bashrc.sh
    dest: /etc/profile.d/bashrc.sh
    owner: root
    group: root
    mode: 0755
  sudo: yes

- name: bash aliases
  copy:
    src: etc/profile.d/bash_aliases.sh
    dest: /etc/profile.d/bash_aliases.sh
    owner: root
    group: root
    mode: 0755
  sudo: yes

- group: name=dev state=present
  sudo: yes

- user: name={{ item }} groups=dev append=yes
  with_items: common_dev_users
  sudo: yes
