---

- include: workspace.yml
  tags: [webrtc-dev]

- include: checkout.yml
  when: not webrtc_dev_skip_checkout
  tags: [webrtc-dev, webrtc-dev-checkout]

- include: patch.yml
  when: not webrtc_dev_skip_checkout
  tags: [webrtc-dev, webrtc-dev-patch]

- name: install arm sysroot
  shell: "PATH={{ chromium_dev_root }}/depot_tools/:${PATH}; source /etc/profile && src/chromium/src/chrome/installer/linux/sysroot_scripts/install-debian.wheezy.sysroot.py --arch=arm"
  args:
    chdir: "{{ webrtc_dev_root }}/webrtc"
    executable: /bin/bash
    creates: "{{ webrtc_dev_root }}/webrtc/src/chromium/src/chrome/installer/linux/debian_wheezy_arm-sysroot"
  when: not webrtc_dev_skip_checkout
  tags: [webrtc-dev, webrtc-dev-sysroot]
