---
- name: create build directory
  file: path=/opt/webrtc state=directory owner=root group=root mode=0777
  sudo: yes
  tags: [webrtc-dev]

- name: fetching (can take HOURS!)
  shell: source /etc/profile && fetch webrtc
  args:
    chdir: /opt/webrtc
    creates: /opt/webrtc/src
    executable: /bin/bash
  tags: [webrtc-dev]

- name: checkout
  shell: source /etc/profile && git checkout master && git pull
  args:
    chdir: /opt/webrtc/src
    executable: /bin/bash
  tags: [webrtc-dev]

- name: copy build/common.gypi sysroot patch
  copy: src=webrtc_build_common_gypi_sysroot.patch dest=/opt/webrtc_build_common_gypi_sysroot.patch mode=0644
  tags: [webrtc-dev]
  sudo: yes

- name: check build/common.gypi sysroot patch
  command: git apply --check /opt/webrtc_build_common_gypi_sysroot.patch
  args:
    chdir: /opt/webrtc/src/build
  register: git_apply_check_sysroot_patch
  failed_when: git_apply_check_sysroot_patch.rc not in [0, 1]
  tags: [webrtc-dev]

- name: apply build/common.gypi sysroot patch
  command: git apply /opt/webrtc_build_common_gypi_sysroot.patch
  args:
    chdir: /opt/webrtc/src/build
  when: git_apply_check_sysroot_patch.rc == 0
  tags: [webrtc-dev]

- name: syncing (can take HOURS!)
  shell: source /etc/profile && gclient sync
  args:
    chdir: /opt/webrtc
    executable: /bin/bash
  tags: [webrtc-dev]
