---
- name: create build directory
  file: path=/opt/webrtc state=directory group={{ webrtc_dev_group }} mode=0775
  sudo: yes
  tags: [webrtc-dev]

- name: fetching (can take HOURS!)
  shell: source /etc/profile && fetch webrtc
  args:
    chdir: /opt/webrtc
    executable: /bin/bash
    creates: /opt/webrtc/src
  register: fetch
  tags: [webrtc-dev]

- name: create gclient conf
  template: src=gclient.j2 dest=/opt/webrtc/.gclient mode=0644
  tags: [webrtc-dev]

- name: sync (can take HOURS!)
  shell: source /etc/profile && gclient sync
  args:
    chdir: /opt/webrtc
    executable: /bin/bash
  when: fetch|changed
  tags: [webrtc-dev]

- name: copy build/common.gypi sysroot patch
  copy: src=webrtc_build_common_gypi_sysroot.patch dest=/opt/webrtc_build_common_gypi_sysroot.patch mode=0644
  tags: [webrtc-dev]
  sudo: yes

- name: check build/common.gypi sysroot patch
  command: git apply --check /opt/webrtc_build_common_gypi_sysroot.patch
  args:
    chdir: /opt/webrtc/src/build
  register: git_apply_check_sysroot_patch
  failed_when: git_apply_check_sysroot_patch.rc not in [0, 1]
  tags: [webrtc-dev]

- name: apply build/common.gypi sysroot patch
  command: git apply /opt/webrtc_build_common_gypi_sysroot.patch
  args:
    chdir: /opt/webrtc/src/build
  when: git_apply_check_sysroot_patch.rc == 0
  tags: [webrtc-dev]

- name: syncing (can take HOURS!)
  shell: source /etc/profile && gclient sync
  args:
    chdir: /opt/webrtc
    executable: /bin/bash
  tags: [webrtc-dev]

- name: install arm sysroot
  shell: source /etc/profile && src/chromium/src/chrome/installer/linux/sysroot_scripts/install-debian.wheezy.sysroot.py --arch=arm
  args:
    chdir: /opt/webrtc
    executable: /bin/bash
    creates: /opt/webrtc/src/chromium/src/chrome/installer/linux/debian_wheezy_arm-sysroot
  tags: [webrtc-dev, sysroot]
