---

# webrtc/api/api.gyp

- name: copy webrtc/api/api.gyp patch
  copy: >
    src=webrtc_api_gyp_libjingle.patch
    dest="{{ webrtc_dev_root }}/webrtc/webrtc_api_gyp_libjingle.patch"
    mode=0664

- name: check webrtc/api/api.gyp patch
  command: git apply --check {{ webrtc_dev_root }}/webrtc/webrtc_api_gyp_libjingle.patch
  args:
    chdir: "{{ webrtc_dev_root }}/webrtc/src"
  register: git_apply_check_libjingle_targets_patch
  failed_when: git_apply_check_libjingle_targets_patch.rc not in [0, 1]
  changed_when: git_apply_check_libjingle_targets_patch.rc == 0

- name: apply webrtc/api/api.gyp patch
  command: git apply {{ webrtc_dev_root }}/webrtc/webrtc_api_gyp_libjingle.patch
  args:
    chdir: "{{ webrtc_dev_root }}/webrtc/src"
  when: git_apply_check_libjingle_targets_patch.rc == 0
  
- name: commit webrtc/api/api.gyp patch
  shell: git add webrtc/api/api.gyp && git commit -m "add libjingle targets"
  args:
    chdir: "{{ webrtc_dev_root }}/webrtc/src"
  when: git_apply_check_libjingle_targets_patch.rc == 0
